
let { generatePackageManifests } = require('../src/packageBuilder.js'),
    codeResult = require('./fixtures/codeInstallerResult.json'),
    prebidResult = require('./fixtures/prebidInstallerResult.json'),
    compiledConfig = require('./fixtures/compiledConfig.json');

describe('the builder', () => {

    it('should generate valid manifest with code and prebid installer results', () => {
        let manifests = generatePackageManifests(compiledConfig, prebidResult, codeResult, './build/packages');

        expect(manifests).toEqual({
            "pub2-site1.js": {
                "main": "../prebid/0.27.1/prebid-core.js",
                "modules": [
                    "../prebid/0.27.1/appnexusBidAdapter.js"
                ],
                "code": [
                    "../code/34cb974.js"
                ],
                "postfix": "pbjs.processQueue();"
            },
            "pub2-site2.json": {
                "main": "../prebid/0.27.1/prebid-core.js",
                "modules": {
                    "aardvarkBidAdapter": "../prebid/0.27.1/aardvarkBidAdapter.js",
                    "adbladeBidAdapter": "../prebid/0.27.1/adbladeBidAdapter.js",
                    "adbundBidAdapter": "../prebid/0.27.1/adbundBidAdapter.js",
                    "adbutlerBidAdapter": "../prebid/0.27.1/adbutlerBidAdapter.js",
                    "adequantBidAdapter": "../prebid/0.27.1/adequantBidAdapter.js",
                    "adformBidAdapter": "../prebid/0.27.1/adformBidAdapter.js",
                    "adkernelBidAdapter": "../prebid/0.27.1/adkernelBidAdapter.js",
                    "admediaBidAdapter": "../prebid/0.27.1/admediaBidAdapter.js",
                    "admixerBidAdapter": "../prebid/0.27.1/admixerBidAdapter.js",
                    "adsupplyBidAdapter": "../prebid/0.27.1/adsupplyBidAdapter.js",
                    "adyoulikeBidAdapter": "../prebid/0.27.1/adyoulikeBidAdapter.js",
                    "aolBidAdapter": "../prebid/0.27.1/aolBidAdapter.js",
                    "appnexusAnalyticsAdapter": "../prebid/0.27.1/appnexusAnalyticsAdapter.js",
                    "appnexusAstBidAdapter": "../prebid/0.27.1/appnexusAstBidAdapter.js",
                    "appnexusBidAdapter": "../prebid/0.27.1/appnexusBidAdapter.js",
                    "atomxBidAdapter": "../prebid/0.27.1/atomxBidAdapter.js",
                    "audienceNetworkBidAdapter": "../prebid/0.27.1/audienceNetworkBidAdapter.js",
                    "beachfrontBidAdapter": "../prebid/0.27.1/beachfrontBidAdapter.js",
                    "bidfluenceBidAdapter": "../prebid/0.27.1/bidfluenceBidAdapter.js",
                    "brightcomBidAdapter": "../prebid/0.27.1/brightcomBidAdapter.js",
                    "c1xBidAdapter": "../prebid/0.27.1/c1xBidAdapter.js",
                    "carambolaBidAdapter": "../prebid/0.27.1/carambolaBidAdapter.js",
                    "centroBidAdapter": "../prebid/0.27.1/centroBidAdapter.js",
                    "conversantBidAdapter": "../prebid/0.27.1/conversantBidAdapter.js",
                    "coxBidAdapter": "../prebid/0.27.1/coxBidAdapter.js",
                    "criteoBidAdapter": "../prebid/0.27.1/criteoBidAdapter.js",
                    "dfpAdServerVideo": "../prebid/0.27.1/dfpAdServerVideo.js",
                    "districtmDMXBidAdapter": "../prebid/0.27.1/districtmDMXBidAdapter.js",
                    "eplanningBidAdapter": "../prebid/0.27.1/eplanningBidAdapter.js",
                    "essensBidAdapter": "../prebid/0.27.1/essensBidAdapter.js",
                    "express": "../prebid/0.27.1/express.js",
                    "featureforwardBidAdapter": "../prebid/0.27.1/featureforwardBidAdapter.js",
                    "fidelityBidAdapter": "../prebid/0.27.1/fidelityBidAdapter.js",
                    "getintentBidAdapter": "../prebid/0.27.1/getintentBidAdapter.js",
                    "googleAnalyticsAdapter": "../prebid/0.27.1/googleAnalyticsAdapter.js",
                    "gumgumBidAdapter": "../prebid/0.27.1/gumgumBidAdapter.js",
                    "hiromediaBidAdapter": "../prebid/0.27.1/hiromediaBidAdapter.js",
                    "huddledmassesBidAdapter": "../prebid/0.27.1/huddledmassesBidAdapter.js",
                    "imonomyBidAdapter": "../prebid/0.27.1/imonomyBidAdapter.js",
                    "indexExchangeBidAdapter": "../prebid/0.27.1/indexExchangeBidAdapter.js",
                    "inneractiveBidAdapter": "../prebid/0.27.1/inneractiveBidAdapter.js",
                    "innityBidAdapter": "../prebid/0.27.1/innityBidAdapter.js",
                    "jcmBidAdapter": "../prebid/0.27.1/jcmBidAdapter.js",
                    "justpremiumBidAdapter": "../prebid/0.27.1/justpremiumBidAdapter.js",
                    "kargoBidAdapter": "../prebid/0.27.1/kargoBidAdapter.js",
                    "komoonaBidAdapter": "../prebid/0.27.1/komoonaBidAdapter.js",
                    "kruxlinkBidAdapter": "../prebid/0.27.1/kruxlinkBidAdapter.js",
                    "lifestreetBidAdapter": "../prebid/0.27.1/lifestreetBidAdapter.js",
                    "mantisBidAdapter": "../prebid/0.27.1/mantisBidAdapter.js",
                    "marsmediaAnalyticsAdapter": "../prebid/0.27.1/marsmediaAnalyticsAdapter.js",
                    "marsmediaBidAdapter": "../prebid/0.27.1/marsmediaBidAdapter.js",
                    "memeglobalBidAdapter": "../prebid/0.27.1/memeglobalBidAdapter.js",
                    "mobfoxBidAdapter": "../prebid/0.27.1/mobfoxBidAdapter.js",
                    "nginadBidAdapter": "../prebid/0.27.1/nginadBidAdapter.js",
                    "openxBidAdapter": "../prebid/0.27.1/openxBidAdapter.js",
                    "piximediaBidAdapter": "../prebid/0.27.1/piximediaBidAdapter.js",
                    "platformioBidAdapter": "../prebid/0.27.1/platformioBidAdapter.js",
                    "polluxBidAdapter": "../prebid/0.27.1/polluxBidAdapter.js",
                    "prebidServerBidAdapter": "../prebid/0.27.1/prebidServerBidAdapter.js",
                    "pubgearsBidAdapter": "../prebid/0.27.1/pubgearsBidAdapter.js",
                    "pubmaticBidAdapter": "../prebid/0.27.1/pubmaticBidAdapter.js",
                    "pubwiseAnalyticsAdapter": "../prebid/0.27.1/pubwiseAnalyticsAdapter.js",
                    "pulsepointAnalyticsAdapter": "../prebid/0.27.1/pulsepointAnalyticsAdapter.js",
                    "pulsepointBidAdapter": "../prebid/0.27.1/pulsepointBidAdapter.js",
                    "pulsepointLiteBidAdapter": "../prebid/0.27.1/pulsepointLiteBidAdapter.js",
                    "quantcastBidAdapter": "../prebid/0.27.1/quantcastBidAdapter.js",
                    "rhythmoneBidAdapter": "../prebid/0.27.1/rhythmoneBidAdapter.js",
                    "roxotAnalyticsAdapter": "../prebid/0.27.1/roxotAnalyticsAdapter.js",
                    "roxotBidAdapter": "../prebid/0.27.1/roxotBidAdapter.js",
                    "rubiconBidAdapter": "../prebid/0.27.1/rubiconBidAdapter.js",
                    "sekindoUMBidAdapter": "../prebid/0.27.1/sekindoUMBidAdapter.js",
                    "serverbidBidAdapter": "../prebid/0.27.1/serverbidBidAdapter.js",
                    "sharethroughAnalyticsAdapter": "../prebid/0.27.1/sharethroughAnalyticsAdapter.js",
                    "sharethroughBidAdapter": "../prebid/0.27.1/sharethroughBidAdapter.js",
                    "smartadserverBidAdapter": "../prebid/0.27.1/smartadserverBidAdapter.js",
                    "smartyadsBidAdapter": "../prebid/0.27.1/smartyadsBidAdapter.js",
                    "sonobiBidAdapter": "../prebid/0.27.1/sonobiBidAdapter.js",
                    "sovrnBidAdapter": "../prebid/0.27.1/sovrnBidAdapter.js",
                    "spotxBidAdapter": "../prebid/0.27.1/spotxBidAdapter.js",
                    "springserveBidAdapter": "../prebid/0.27.1/springserveBidAdapter.js",
                    "stickyadstvBidAdapter": "../prebid/0.27.1/stickyadstvBidAdapter.js",
                    "tapsenseBidAdapter": "../prebid/0.27.1/tapsenseBidAdapter.js",
                    "thoughtleadrBidAdapter": "../prebid/0.27.1/thoughtleadrBidAdapter.js",
                    "trionBidAdapter": "../prebid/0.27.1/trionBidAdapter.js",
                    "tripleliftBidAdapter": "../prebid/0.27.1/tripleliftBidAdapter.js",
                    "twengaBidAdapter": "../prebid/0.27.1/twengaBidAdapter.js",
                    "ucfunnelBidAdapter": "../prebid/0.27.1/ucfunnelBidAdapter.js",
                    "underdogmediaBidAdapter": "../prebid/0.27.1/underdogmediaBidAdapter.js",
                    "unrulyBidAdapter": "../prebid/0.27.1/unrulyBidAdapter.js",
                    "vertamediaBidAdapter": "../prebid/0.27.1/vertamediaBidAdapter.js",
                    "vertozBidAdapter": "../prebid/0.27.1/vertozBidAdapter.js",
                    "wideorbitBidAdapter": "../prebid/0.27.1/wideorbitBidAdapter.js",
                    "widespaceBidAdapter": "../prebid/0.27.1/widespaceBidAdapter.js",
                    "xhbBidAdapter": "../prebid/0.27.1/xhbBidAdapter.js",
                    "yieldbotBidAdapter": "../prebid/0.27.1/yieldbotBidAdapter.js"
                },
                "code": {
                    "adUnits": "../code/34cb974.js",
                    "digitrust": "../code/e775040.js"
                },
                "postfix": "pbjs.processQueue();"
            },
            "pub3-site1.js": {
                "main": "../prebid/1.0.0/prebid-core.js",
                "modules": [
                    "../prebid/1.0.0/appnexusBidAdapter.js",
                    "../prebid/1.0.0/rubiconBidAdapter.js"
                ],
                "postfix": "pbjs.processQueue();"
            },
            "pub3-site2.json": {
                "main": "../prebid/1.0.0/prebid-core.js",
                "modules": {
                    "33acrossBidAdapter": "../prebid/1.0.0/33acrossBidAdapter.js",
                    "a4gBidAdapter": "../prebid/1.0.0/a4gBidAdapter.js",
                    "adbutlerBidAdapter": "../prebid/1.0.0/adbutlerBidAdapter.js",
                    "adkernelAdnAnalyticsAdapter": "../prebid/1.0.0/adkernelAdnAnalyticsAdapter.js",
                    "adkernelAdnBidAdapter": "../prebid/1.0.0/adkernelAdnBidAdapter.js",
                    "adkernelBidAdapter": "../prebid/1.0.0/adkernelBidAdapter.js",
                    "adoceanBidAdapter": "../prebid/1.0.0/adoceanBidAdapter.js",
                    "adomikAnalyticsAdapter": "../prebid/1.0.0/adomikAnalyticsAdapter.js",
                    "adxcgAnalyticsAdapter": "../prebid/1.0.0/adxcgAnalyticsAdapter.js",
                    "adxcgBidAdapter": "../prebid/1.0.0/adxcgBidAdapter.js",
                    "aolBidAdapter": "../prebid/1.0.0/aolBidAdapter.js",
                    "appnexusAnalyticsAdapter": "../prebid/1.0.0/appnexusAnalyticsAdapter.js",
                    "appnexusBidAdapter": "../prebid/1.0.0/appnexusBidAdapter.js",
                    "arteebeeBidAdapter": "../prebid/1.0.0/arteebeeBidAdapter.js",
                    "audienceNetworkBidAdapter": "../prebid/1.0.0/audienceNetworkBidAdapter.js",
                    "beachfrontBidAdapter": "../prebid/1.0.0/beachfrontBidAdapter.js",
                    "bridgewellBidAdapter": "../prebid/1.0.0/bridgewellBidAdapter.js",
                    "conversantBidAdapter": "../prebid/1.0.0/conversantBidAdapter.js",
                    "currency": "../prebid/1.0.0/currency.js",
                    "dfpAdServerVideo": "../prebid/1.0.0/dfpAdServerVideo.js",
                    "express": "../prebid/1.0.0/express.js",
                    "fidelityBidAdapter": "../prebid/1.0.0/fidelityBidAdapter.js",
                    "getintentBidAdapter": "../prebid/1.0.0/getintentBidAdapter.js",
                    "googleAnalyticsAdapter": "../prebid/1.0.0/googleAnalyticsAdapter.js",
                    "huddledmassesBidAdapter": "../prebid/1.0.0/huddledmassesBidAdapter.js",
                    "improvedigitalBidAdapter": "../prebid/1.0.0/improvedigitalBidAdapter.js",
                    "jcmBidAdapter": "../prebid/1.0.0/jcmBidAdapter.js",
                    "justpremiumBidAdapter": "../prebid/1.0.0/justpremiumBidAdapter.js",
                    "kargoBidAdapter": "../prebid/1.0.0/kargoBidAdapter.js",
                    "komoonaBidAdapter": "../prebid/1.0.0/komoonaBidAdapter.js",
                    "kummaBidAdapter": "../prebid/1.0.0/kummaBidAdapter.js",
                    "marsmediaAnalyticsAdapter": "../prebid/1.0.0/marsmediaAnalyticsAdapter.js",
                    "mobfoxBidAdapter": "../prebid/1.0.0/mobfoxBidAdapter.js",
                    "nanointeractiveBidAdapter": "../prebid/1.0.0/nanointeractiveBidAdapter.js",
                    "openxBidAdapter": "../prebid/1.0.0/openxBidAdapter.js",
                    "optimaticBidAdapter": "../prebid/1.0.0/optimaticBidAdapter.js",
                    "platformioBidAdapter": "../prebid/1.0.0/platformioBidAdapter.js",
                    "polluxBidAdapter": "../prebid/1.0.0/polluxBidAdapter.js",
                    "prebidServerBidAdapter": "../prebid/1.0.0/prebidServerBidAdapter.js",
                    "pubwiseAnalyticsAdapter": "../prebid/1.0.0/pubwiseAnalyticsAdapter.js",
                    "pulsepointAnalyticsAdapter": "../prebid/1.0.0/pulsepointAnalyticsAdapter.js",
                    "pulsepointBidAdapter": "../prebid/1.0.0/pulsepointBidAdapter.js",
                    "quantcastBidAdapter": "../prebid/1.0.0/quantcastBidAdapter.js",
                    "readpeakBidAdapter": "../prebid/1.0.0/readpeakBidAdapter.js",
                    "rhythmoneBidAdapter": "../prebid/1.0.0/rhythmoneBidAdapter.js",
                    "roxotAnalyticsAdapter": "../prebid/1.0.0/roxotAnalyticsAdapter.js",
                    "rtbdemandBidAdapter": "../prebid/1.0.0/rtbdemandBidAdapter.js",
                    "rubiconBidAdapter": "../prebid/1.0.0/rubiconBidAdapter.js",
                    "s2sTesting": "../prebid/1.0.0/s2sTesting.js",
                    "sekindoUMBidAdapter": "../prebid/1.0.0/sekindoUMBidAdapter.js",
                    "serverbidBidAdapter": "../prebid/1.0.0/serverbidBidAdapter.js",
                    "sharethroughAnalyticsAdapter": "../prebid/1.0.0/sharethroughAnalyticsAdapter.js",
                    "sharethroughBidAdapter": "../prebid/1.0.0/sharethroughBidAdapter.js",
                    "somoaudienceBidAdapter": "../prebid/1.0.0/somoaudienceBidAdapter.js",
                    "sovrnBidAdapter": "../prebid/1.0.0/sovrnBidAdapter.js",
                    "trionBidAdapter": "../prebid/1.0.0/trionBidAdapter.js",
                    "trustxBidAdapter": "../prebid/1.0.0/trustxBidAdapter.js",
                    "underdogmediaBidAdapter": "../prebid/1.0.0/underdogmediaBidAdapter.js",
                    "undertoneBidAdapter": "../prebid/1.0.0/undertoneBidAdapter.js",
                    "vertamediaBidAdapter": "../prebid/1.0.0/vertamediaBidAdapter.js"
                },
                "code": {
                    "adUnits": "../code/10a065c.js",
                    "digitrust": "../code/e775040.js"
                },
                "postfix": "pbjs.processQueue();"
            },
            "pub4-site1.js": {
                "main": "../prebid/0.29.0/prebid-core.js",
                "modules": [
                    "../prebid/0.29.0/appnexusBidAdapter.js",
                    "../prebid/0.29.0/rubiconBidAdapter.js"
                ],
                "postfix": "pbjs.processQueue();"
            },
            "pub4-site1.json": {
                "main": "../prebid/0.29.0/prebid-core.js",
                "modules": {
                    "aardvarkBidAdapter": "../prebid/0.29.0/aardvarkBidAdapter.js",
                    "adbladeBidAdapter": "../prebid/0.29.0/adbladeBidAdapter.js",
                    "adbundBidAdapter": "../prebid/0.29.0/adbundBidAdapter.js",
                    "adbutlerBidAdapter": "../prebid/0.29.0/adbutlerBidAdapter.js",
                    "adequantBidAdapter": "../prebid/0.29.0/adequantBidAdapter.js",
                    "adformBidAdapter": "../prebid/0.29.0/adformBidAdapter.js",
                    "adkernelBidAdapter": "../prebid/0.29.0/adkernelBidAdapter.js",
                    "admediaBidAdapter": "../prebid/0.29.0/admediaBidAdapter.js",
                    "admixerBidAdapter": "../prebid/0.29.0/admixerBidAdapter.js",
                    "adsupplyBidAdapter": "../prebid/0.29.0/adsupplyBidAdapter.js",
                    "adxcgBidAdapter": "../prebid/0.29.0/adxcgBidAdapter.js",
                    "adyoulikeBidAdapter": "../prebid/0.29.0/adyoulikeBidAdapter.js",
                    "aerservBidAdapter": "../prebid/0.29.0/aerservBidAdapter.js",
                    "aolBidAdapter": "../prebid/0.29.0/aolBidAdapter.js",
                    "appnexusAnalyticsAdapter": "../prebid/0.29.0/appnexusAnalyticsAdapter.js",
                    "appnexusAstBidAdapter": "../prebid/0.29.0/appnexusAstBidAdapter.js",
                    "appnexusBidAdapter": "../prebid/0.29.0/appnexusBidAdapter.js",
                    "atomxBidAdapter": "../prebid/0.29.0/atomxBidAdapter.js",
                    "audienceNetworkBidAdapter": "../prebid/0.29.0/audienceNetworkBidAdapter.js",
                    "beachfrontBidAdapter": "../prebid/0.29.0/beachfrontBidAdapter.js",
                    "bidfluenceBidAdapter": "../prebid/0.29.0/bidfluenceBidAdapter.js",
                    "brightcomBidAdapter": "../prebid/0.29.0/brightcomBidAdapter.js",
                    "c1xBidAdapter": "../prebid/0.29.0/c1xBidAdapter.js",
                    "carambolaBidAdapter": "../prebid/0.29.0/carambolaBidAdapter.js",
                    "centroBidAdapter": "../prebid/0.29.0/centroBidAdapter.js",
                    "conversantBidAdapter": "../prebid/0.29.0/conversantBidAdapter.js",
                    "coxBidAdapter": "../prebid/0.29.0/coxBidAdapter.js",
                    "criteoBidAdapter": "../prebid/0.29.0/criteoBidAdapter.js",
                    "currency": "../prebid/0.29.0/currency.js",
                    "dfpAdServerVideo": "../prebid/0.29.0/dfpAdServerVideo.js",
                    "districtmDMXBidAdapter": "../prebid/0.29.0/districtmDMXBidAdapter.js",
                    "eplanningBidAdapter": "../prebid/0.29.0/eplanningBidAdapter.js",
                    "essensBidAdapter": "../prebid/0.29.0/essensBidAdapter.js",
                    "express": "../prebid/0.29.0/express.js",
                    "featureforwardBidAdapter": "../prebid/0.29.0/featureforwardBidAdapter.js",
                    "fidelityBidAdapter": "../prebid/0.29.0/fidelityBidAdapter.js",
                    "getintentBidAdapter": "../prebid/0.29.0/getintentBidAdapter.js",
                    "googleAnalyticsAdapter": "../prebid/0.29.0/googleAnalyticsAdapter.js",
                    "gumgumBidAdapter": "../prebid/0.29.0/gumgumBidAdapter.js",
                    "hiromediaBidAdapter": "../prebid/0.29.0/hiromediaBidAdapter.js",
                    "huddledmassesBidAdapter": "../prebid/0.29.0/huddledmassesBidAdapter.js",
                    "imonomyBidAdapter": "../prebid/0.29.0/imonomyBidAdapter.js",
                    "improvedigitalBidAdapter": "../prebid/0.29.0/improvedigitalBidAdapter.js",
                    "indexExchangeBidAdapter": "../prebid/0.29.0/indexExchangeBidAdapter.js",
                    "inneractiveBidAdapter": "../prebid/0.29.0/inneractiveBidAdapter.js",
                    "innityBidAdapter": "../prebid/0.29.0/innityBidAdapter.js",
                    "jcmBidAdapter": "../prebid/0.29.0/jcmBidAdapter.js",
                    "justpremiumBidAdapter": "../prebid/0.29.0/justpremiumBidAdapter.js",
                    "kargoBidAdapter": "../prebid/0.29.0/kargoBidAdapter.js",
                    "komoonaBidAdapter": "../prebid/0.29.0/komoonaBidAdapter.js",
                    "kruxlinkBidAdapter": "../prebid/0.29.0/kruxlinkBidAdapter.js",
                    "kummaBidAdapter": "../prebid/0.29.0/kummaBidAdapter.js",
                    "lifestreetBidAdapter": "../prebid/0.29.0/lifestreetBidAdapter.js",
                    "mantisBidAdapter": "../prebid/0.29.0/mantisBidAdapter.js",
                    "marsmediaAnalyticsAdapter": "../prebid/0.29.0/marsmediaAnalyticsAdapter.js",
                    "marsmediaBidAdapter": "../prebid/0.29.0/marsmediaBidAdapter.js",
                    "memeglobalBidAdapter": "../prebid/0.29.0/memeglobalBidAdapter.js",
                    "mobfoxBidAdapter": "../prebid/0.29.0/mobfoxBidAdapter.js",
                    "nginadBidAdapter": "../prebid/0.29.0/nginadBidAdapter.js",
                    "openxBidAdapter": "../prebid/0.29.0/openxBidAdapter.js",
                    "orbitsoftBidAdapter": "../prebid/0.29.0/orbitsoftBidAdapter.js",
                    "piximediaBidAdapter": "../prebid/0.29.0/piximediaBidAdapter.js",
                    "platformioBidAdapter": "../prebid/0.29.0/platformioBidAdapter.js",
                    "polluxBidAdapter": "../prebid/0.29.0/polluxBidAdapter.js",
                    "prebidServerBidAdapter": "../prebid/0.29.0/prebidServerBidAdapter.js",
                    "pubgearsBidAdapter": "../prebid/0.29.0/pubgearsBidAdapter.js",
                    "pubmaticBidAdapter": "../prebid/0.29.0/pubmaticBidAdapter.js",
                    "pubwiseAnalyticsAdapter": "../prebid/0.29.0/pubwiseAnalyticsAdapter.js",
                    "pulsepointAnalyticsAdapter": "../prebid/0.29.0/pulsepointAnalyticsAdapter.js",
                    "pulsepointBidAdapter": "../prebid/0.29.0/pulsepointBidAdapter.js",
                    "pulsepointLiteBidAdapter": "../prebid/0.29.0/pulsepointLiteBidAdapter.js",
                    "quantcastBidAdapter": "../prebid/0.29.0/quantcastBidAdapter.js",
                    "rhythmoneBidAdapter": "../prebid/0.29.0/rhythmoneBidAdapter.js",
                    "roxotAnalyticsAdapter": "../prebid/0.29.0/roxotAnalyticsAdapter.js",
                    "roxotBidAdapter": "../prebid/0.29.0/roxotBidAdapter.js",
                    "rubiconBidAdapter": "../prebid/0.29.0/rubiconBidAdapter.js",
                    "sekindoUMBidAdapter": "../prebid/0.29.0/sekindoUMBidAdapter.js",
                    "serverbidBidAdapter": "../prebid/0.29.0/serverbidBidAdapter.js",
                    "sharethroughAnalyticsAdapter": "../prebid/0.29.0/sharethroughAnalyticsAdapter.js",
                    "sharethroughBidAdapter": "../prebid/0.29.0/sharethroughBidAdapter.js",
                    "smartadserverBidAdapter": "../prebid/0.29.0/smartadserverBidAdapter.js",
                    "smartyadsBidAdapter": "../prebid/0.29.0/smartyadsBidAdapter.js",
                    "sonobiBidAdapter": "../prebid/0.29.0/sonobiBidAdapter.js",
                    "sovrnBidAdapter": "../prebid/0.29.0/sovrnBidAdapter.js",
                    "spotxBidAdapter": "../prebid/0.29.0/spotxBidAdapter.js",
                    "springserveBidAdapter": "../prebid/0.29.0/springserveBidAdapter.js",
                    "stickyadstvBidAdapter": "../prebid/0.29.0/stickyadstvBidAdapter.js",
                    "tapsenseBidAdapter": "../prebid/0.29.0/tapsenseBidAdapter.js",
                    "thoughtleadrBidAdapter": "../prebid/0.29.0/thoughtleadrBidAdapter.js",
                    "tremorBidAdapter": "../prebid/0.29.0/tremorBidAdapter.js",
                    "trionBidAdapter": "../prebid/0.29.0/trionBidAdapter.js",
                    "tripleliftBidAdapter": "../prebid/0.29.0/tripleliftBidAdapter.js",
                    "trustxBidAdapter": "../prebid/0.29.0/trustxBidAdapter.js",
                    "twengaBidAdapter": "../prebid/0.29.0/twengaBidAdapter.js",
                    "ucfunnelBidAdapter": "../prebid/0.29.0/ucfunnelBidAdapter.js",
                    "underdogmediaBidAdapter": "../prebid/0.29.0/underdogmediaBidAdapter.js",
                    "unrulyBidAdapter": "../prebid/0.29.0/unrulyBidAdapter.js",
                    "vertamediaBidAdapter": "../prebid/0.29.0/vertamediaBidAdapter.js",
                    "vertozBidAdapter": "../prebid/0.29.0/vertozBidAdapter.js",
                    "wideorbitBidAdapter": "../prebid/0.29.0/wideorbitBidAdapter.js",
                    "widespaceBidAdapter": "../prebid/0.29.0/widespaceBidAdapter.js",
                    "xhbBidAdapter": "../prebid/0.29.0/xhbBidAdapter.js",
                    "yieldbotBidAdapter": "../prebid/0.29.0/yieldbotBidAdapter.js",
                    "yieldmoBidAdapter": "../prebid/0.29.0/yieldmoBidAdapter.js"
                },
                "postfix": "pbjs.processQueue();"
            }
        });
    })

});